In [1]:
import numpy as np

In [2]:
A = np.array([[2, -1, 3],
              [0, 4, 1]])

B = np.array([[1, 2],
              [-2, 0],
              [5, -3]])

In [3]:
matrix1 = np.dot(A, B)
matrix2 = np.dot(B, A)
print("Matrix A:\n", A, "\nMatrix B:\n", B)
print("\nMatrix '(AB)' is:\n", matrix1)
print("Matrix '(BA)' is:\n", matrix2)


Matrix A:
 [[ 2 -1  3]
 [ 0  4  1]] 
Matrix B:
 [[ 1  2]
 [-2  0]
 [ 5 -3]]

Matrix '(AB)' is:
 [[19 -5]
 [-3 -3]]
Matrix '(BA)' is:
 [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
