In [101]:
import numpy as np

# Step 1: Define a new 4×3 matrix (4 students, 3 subjects: Math, English, Science, History)
scores = np.array([
    [80, 70, 90, ],  # Student 1
    [60, 85, 75, ],  # Student 2
    [95, 88, 92, ],  # Student 3
    [70, 60, 65, ],  # Student 4
])

print("Step 1: Scores Matrix (4 students x 3 subjects):")
print(scores)
print()


Step 1: Scores Matrix (4 students x 3 subjects):
[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]



In [90]:
# Step 2: Total score per student (row-wise sum)
total_scores = np.sum(scores, axis=1)
print("Step 2: Total Scores per Student:")
for i, total in enumerate(total_scores, start=1):
    print(f"Student {i}: {total}")
print()

Step 2: Total Scores per Student:
Student 1: 240
Student 2: 220
Student 3: 275
Student 4: 195



In [91]:
# Step 3: Average score per subject (column-wise mean)
average_per_subject = np.mean(scores, axis=0)
print("Step 3: Average Score per Subject:")
subjects = ["Math", "English", "Science",]
for subj, avg in zip(subjects, average_per_subject):
    print(f"{subj}: {avg:.2f}")
print()

Step 3: Average Score per Subject:
Math: 76.25
English: 75.75
Science: 80.50



In [92]:
# Step 4: Apply scalar weights (Science is 3x more important)
scalar_weights = np.array([1, 1, 3])  # Weights for 3 subjects
weighted_totals = np.sum(scores * scalar_weights, axis=1)

print("Step 4: Weighted Totals (Science x3):")
for i, wt in enumerate(weighted_totals, start=1):
    print(f"Student {i}: {wt}")


Step 4: Weighted Totals (Science x3):
Student 1: 420
Student 2: 370
Student 3: 459
Student 4: 325


In [93]:
# Step 5: Final grades using matrix multiplication with new weights
grade_weights = np.array([0.5, 0.3, 0.2,])
final_grades = np.dot(scores, grade_weights)
print("Step 5: Final Grades (Weighted Average):")
for i, grade in enumerate(final_grades, start=1):
    print(f"Student {i}: {grade:.2f}")
print()

Step 5: Final Grades (Weighted Average):
Student 1: 79.00
Student 2: 70.50
Student 3: 92.30
Student 4: 66.00



In [94]:
# Step 6: Compare Student 3 and Student 4
comparison = scores[2] - scores[3]
print("Step 6: Comparison Between Student 3 and Student 4:")
for subj, diff in zip(subjects, comparison):
    result = "Student 3" if diff > 0 else "Student 4" if diff < 0 else "Equal"
    print(f"{subj}: {result} performed better by {abs(diff)} points")


Step 6: Comparison Between Student 3 and Student 4:
Math: Student 3 performed better by 25 points
English: Student 3 performed better by 28 points
Science: Student 3 performed better by 27 points


In [95]:
import numpy as np

# Step 1: Define a new 5×4 matrix (5 students, 4 subjects: Math, English, Science, Computer)
scores = np.array([
    [80, 70, 90, 85],  # Student 1
    [60, 85, 75, 80],  # Student 2
    [95, 88, 92, 90],  # Student 3
    [70, 60, 65, 70],  # Student 4
    [85, 78, 80, 88]   # Student 5
])

print("Step 1: Scores Matrix (5 students × 4 subjects):")
print(scores)
print()


Step 1: Scores Matrix (5 students × 4 subjects):
[[80 70 90 85]
 [60 85 75 80]
 [95 88 92 90]
 [70 60 65 70]
 [85 78 80 88]]



In [96]:
# Step 2: Total score per student (row-wise sum)
total_scores = np.sum(scores, axis=1)
print("Step 2: Total Scores per Student:")
for i, total in enumerate(total_scores, start=1):
    print(f"Student {i}: {total}")
print()


Step 2: Total Scores per Student:
Student 1: 325
Student 2: 300
Student 3: 365
Student 4: 265
Student 5: 331



In [97]:
# Step 3: Average score per subject (column-wise mean)
average_per_subject = np.mean(scores, axis=0)
print("Step 3: Average Score per Subject:")
subjects = ["Math", "English", "Science", "Computer"]
for subj, avg in zip(subjects, average_per_subject):
    print(f"{subj}: {avg:.2f}")
print()


Step 3: Average Score per Subject:
Math: 78.00
English: 76.20
Science: 80.40
Computer: 82.60



In [98]:
# Step 4: Apply scalar weights (Science is 3× more important)
scalar_weights = np.array([1, 1, 3, 1])
weighted_totals = np.dot(scores, scalar_weights)
print("Step 4: Weighted Totals (Science ×3):")
for i, wt in enumerate(weighted_totals, start=1):
    print(f"Student {i}: {wt}")
print()

Step 4: Weighted Totals (Science ×3):
Student 1: 505
Student 2: 450
Student 3: 549
Student 4: 395
Student 5: 491



In [99]:
# Step 5: Final grades using matrix multiplication with new weights
grade_weights = np.array([0.4, 0.2, 0.3, 0.1])
final_grades = np.dot(scores, grade_weights)
print("Step 5: Final Grades (Weighted Average):")
for i, grade in enumerate(final_grades, start=1):
    print(f"Student {i}: {grade:.2f}")
print()


Step 5: Final Grades (Weighted Average):
Student 1: 81.50
Student 2: 71.50
Student 3: 92.20
Student 4: 66.50
Student 5: 82.40



In [100]:
# Step 6: Compare Student 3 and Student 4
comparison = scores[2] - scores[3]
print("Step 6: Comparison Between Student 3 and Student 4:")
for subj, diff in zip(subjects, comparison):
    result = "Student 3" if diff > 0 else "Student 4" if diff < 0 else "Equal"
    print(f"{subj}: {result} performed better by {abs(diff)} points")


Step 6: Comparison Between Student 3 and Student 4:
Math: Student 3 performed better by 25 points
English: Student 3 performed better by 28 points
Science: Student 3 performed better by 27 points
Computer: Student 3 performed better by 20 points
