***Question 1***

In [48]:
import numpy as np

array = np.random.randint(1, 50, size=(6, 6))
print(array)


[[ 2 38 18  5 34 37]
 [36  4 39  2 26 14]
 [21 44 14 11 25 22]
 [25 29 31 19 39  9]
 [41 42  7 23  7 34]
 [25 12 19  7 33  3]]


***Question 2***

In [49]:
# import numpy as np

# array= np.random.randint(1, 51, (6, 6))
print("Original Array:\n", array)

print("\nFirst two rows:\n", array[:2])

print("\nLast three columns:\n", array[:, 3:])

print("\nEven numbers:\n", array[array % 2 == 0])


Original Array:
 [[ 2 38 18  5 34 37]
 [36  4 39  2 26 14]
 [21 44 14 11 25 22]
 [25 29 31 19 39  9]
 [41 42  7 23  7 34]
 [25 12 19  7 33  3]]

First two rows:
 [[ 2 38 18  5 34 37]
 [36  4 39  2 26 14]]

Last three columns:
 [[ 5 34 37]
 [ 2 26 14]
 [11 25 22]
 [19 39  9]
 [23  7 34]
 [ 7 33  3]]

Even numbers:
 [ 2 38 18 34 36  4  2 26 14 44 14 22 42 34 12]


***Question 3***